### ISSUE TITLE
page for e-mail confirmation 

### ISSUE THREAD

**Issue by vgeorge** [codigourbano/pnete-monitor#29]
A new user receive a link like this in his e-mail:

http://localhost:3000/confirmar-email/?token=71dd71645f6a2306ff8be2e78bfafa954d3832db&uid=5648bf3e81e99de5127223a6

The page has to call endpoint /users/confirm and show the result to the user.

**Comment by vgeorge** [comment]
Also he could set a password at this page.

**Comment by miguelpeixe** [comment]
the password should be sent as postData? whats the property name?

**Comment by vgeorge** [comment]
property is `password`, any way you send should work, preferable via post data

**Comment by miguelpeixe** [comment]
there's no postData for `confirm` and model doens't expose the password as parameter on the documentation
