### ISSUE TITLE
GET axis/:id/organizations route

### ISSUE THREAD

**Issue by miguelpeixe** [codigourbano/pnete-monitor#30]
get list of organizations related to the axis using indicator relationship data

**Comment by vgeorge** [comment]
Use GET /axis/:id route with filter={"include": {"indicators": "organizations"}}, e. g.:

http://localhost:3000/api/v1/axes/2?filter=%7B%22include%22%3A%20%7B%22indicators%22%3A%20%22organizations%22%7D%7D

It will probably return repeated organizations, but loopback doesn't offer a better way to fetch this info.

**Comment by vgeorge** [comment]
GET /axis/:id/organizations is available now
